### PR TITLE
Fix: ruby 3 upgrade behaviour change when using *args, **kwargs in method args 

### PR DESCRIPTION
**Pull request by bharathtorch**
Tasmania was upgraded to ruby 3.3.3, couple of unit tests failed w.r.t broadcast matcher defined in everwise/wisper-rspec.
Issue due to behaviour change in usage of *args and **kwargs together in method parameters.
Bug link: https://bugs.ruby-lang.org/issues/20180

### CODE REVIEW

**Review by jwoldan — COMMENTED** [review]
I don't 100% understand why this works, but assuming it does I'm good with this change.  Should we keep the variable names the same as before (`name, args, kwargs` instead of `name, new_args, new_kwargs`)?

**Review by coreymaher — COMMENTED** [review]
Should we add some tests to verify the fixes?
Also it looks like we haven't set up this repo to automatically run the tests, have you confirmed that all of the existing tests pass?

**Comment by bharathtorch** [comment]
@coreymaher @jwoldan 

When kwargs is empty and using like this `[method.name.to_s, *args, **kwargs]` 
with method name is event_type, args is event_obj, kwargs is nil
produces different results in 
```
ruby 3.2.3 => ["event_type", Event Obj, {}]
ruby 3.3.3 => ["event_type", Event Obj]
```

So made a change to handle this now the tests in tasmania and tests in this repo everything passes

Below is the example tried with breakpoints

`@broadcast_events << [method_name.to_s, *args, **kwargs]`
https://github.com/everwise/wisper-rspec/blob/master/lib/wisper/rspec/matchers.rb#L24

In 3.3.3
In this assignment
https://github.com/everwise/wisper-rspec/blob/master/lib/wisper/rspec/matchers.rb#L24

event_params value is
```
 pry(#<Wisper::RSpec::EventRecorder>)> event_params
=> ["event_type", #<EventService::Event:0x000000016b5b5f60 id: nil, event_type: "event_type", payload: {"key"=>"value"}, backfilled_at: nil, created_at: nil, updated_at: nil>]
```

when assigning
```
[2] pry(#<Wisper::RSpec::EventRecorder>)> name, *args, kwargs = event_params
```


name was assigned properly
```
[3] pry(#<Wisper::RSpec::EventRecorder>)> name
=> "event_type"
```

args was not assigned, 
```
[4] pry(#<Wisper::RSpec::EventRecorder>)> args
=> []
```

but it was supposed to be `#<EventService::Event:0x000000016b5b5f60 id: nil, event_type: "event_type", payload: {"key"=>"value"}, backfilled_at: nil, created_at: nil, updated_at: nil>`


kwargs supposed to be empty
```
[5] pry(#<Wisper::RSpec::EventRecorder>)> kwargs
=> #<EventService::Event:0x000000016b5b5f60 id: nil, event_type: "event_type", payload: {"key"=>"value"}, backfilled_at: nil, created_at: nil, updated_at: nil>
```

but it got assigned with event object

**When tried with ruby 3.2.3**

```
[1] pry(#<Wisper::RSpec::EventRecorder>)> event_params
=> ["event_type", #<EventService::Event:0x000000011dddf5e0 id: nil, event_type: "event_type", payload: {"key"=>"value"}, backfilled_at: nil, created_at: nil, updated_at: nil>, {}]

[2] pry(#<Wisper::RSpec::EventRecorder>)> name
=> nil

[3] pry(#<Wisper::RSpec::EventRecorder>)> name, *args, kwargs = event_params
=> ["event_type", #<EventService::Event:0x000000011dddf5e0 id: nil, event_type: "event_type", payload: {"key"=>"value"}, backfilled_at: nil, created_at: nil, updated_at: nil>, {}]

[4] pry(#<Wisper::RSpec::EventRecorder>)> name
=> "event_type"

[5] pry(#<Wisper::RSpec::EventRecorder>)> args
=> [#<EventService::Event:0x000000011dddf5e0 id: nil, event_type: "event_type", payload: {"key"=>"value"}, backfilled_at: nil, created_at: nil, updated_at: nil>]

[6] pry(#<Wisper::RSpec::EventRecorder>)> kwargs
=> {}
```

**Review by jwoldan — COMMENTED** [review]
@bharathtorch is this fix now intended to work across both Ruby 3.2.3 and 3.3.3?  Mainly wondering why this has changed from the previous fix you attempted.

I wonder, would it make sense for us to update `.ruby-version` here and only support 3.3.3 and beyond?

**Comment by bharathtorch** [comment]
@jwoldan 
Yes
> is this fix now intended to work across both Ruby 3.2.3 and 3.3.3?

The previous fix not completely correct because it made the tasmania tests to pass, but had couple of failed tests in this repo
> Mainly wondering why this has changed from the previous fix you attempted.

Yeah can be updated in .ruby-version, should not have any issues
> I wonder, would it make sense for us to update .ruby-version here and only support 3.3.3 and beyond?

**Comment by bharathtorch** [comment]
@jwoldan Updated .ruby-version file and adde 3.3 in the unit test github workflow

**Review by jwoldan — APPROVED** [review]

**Pull request merged**
